version: '3.8'
services:
  # web-server nginx
  larave_nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8080:80
    volumes:
    - ./laravel_src:/var/www/html
    - ./laravel_nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - laravel_php
  
  # php(ComposerとNodeのコンテナでもある)
  laravel_php:
    container_name: 'laravel_php'
    build: ./laravel_php
    ports:
      - '9000'
    depends_on:
      - laravel_mysql
    restart: always
    tty: true
    volumes:
      - ./laravel_src:/var/www/html
  
  # MySQL
  laravel_mysql:
    container_name: 'laravel_mysql'
    build: ./laravel_mysql
    ports:
      - '13306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel
      TZ: 'Asia/Tokyo'
    volumes:
      - datastore:/var/lib/mysql
      - ./laravel_mysql/logs:/var/log/mysql
    
  # cron専用コンテナ
  # このコンテナから、phpのコンテナで、commandを実行する
  # ホストマシンにある/var/run/docker.sockをマウントして、操作する
  laravel_cron:
    container_name: 'laravel_cron'
    build: ./laravel_cron
    volumes: 
      - "./laravel_cron/crontabs/cron_test:/var/spool/cron/crontabs/cron_test"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  datastore: